version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/local/api/Dockerfile
    container_name: local-api
    command: ["sleep", "40"]
    env_file: docker/local/api/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/code:z

  redis:
    hostname: redis
    image: redis:alpine
    container_name: local-redis
    ports:
      - "6379:6379"
    volumes:
      - local_redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass devpassword
    networks:
      - proxy-api

networks:
  proxy-api:
    driver: bridge

volumes:
  local_redis_data: {}
